removed sudo

diff --git a/linux/mkbench b/linux/mkbench
--- a/linux/mkbench
+++ b/linux/mkbench
@@ -54,8 +54,12 @@ if [[ ! -a $baseinitrd ]]; then
   exit -1
 fi
 
-sudo cp $kernel $dir
-sudo chmod 744 $dir/$(basename $kernel)
+if ! cp $kernel $dir; then
+  echo "ERROR: cp $kernel $dir failed"
+  exit -1
+fi
+
+chmod 744 $dir/$(basename $kernel)
 
 mkdir $dir/root
 (cd $dir/root; gunzip -c $baseinitrd | cpio -id)
